api_platform:
    title: 'Movies API'
    description: 'API to find every movie has you want'
    version: 2.0.0
    enable_swagger_ui: true
    use_symfony_listeners: true
    enable_re_doc: true
    validator:
        query_parameter_validation: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonapi: ['application/vnd.api+json']
        jsonld: ['application/ld+json']
       